In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "x": [10, 15, 20, 25, 30, 35, 40, 45]
})

df

    x
0  10
1  15
2  20
3  25
4  30
5  35
6  40
7  45

### Equal-Width Discretization

In [2]:
df["x_eq_width"] = pd.cut(df["x"], bins=3, labels=False, include_lowest=True)
df

    x  x_eq_width
0  10           0
1  15           0
2  20           0
3  25           1
4  30           1
5  35           2
6  40           2
7  45           2

Remove `labels=False` to show the intervals.

In [3]:
df["x_eq_width_intervals"] = pd.cut(df["x"], bins=3, include_lowest=True)
df

    x  x_eq_width x_eq_width_intervals
0  10           0      (9.964, 21.667]
1  15           0      (9.964, 21.667]
2  20           0      (9.964, 21.667]
3  25           1     (21.667, 33.333]
4  30           1     (21.667, 33.333]
5  35           2       (33.333, 45.0]
6  40           2       (33.333, 45.0]
7  45           2       (33.333, 45.0]

### Equal-Frequency Discretization

In [4]:
df["x_eq_freq"] = pd.qcut(df["x"], q=3, labels=False)
df

    x  x_eq_width x_eq_width_intervals  x_eq_freq
0  10           0      (9.964, 21.667]          0
1  15           0      (9.964, 21.667]          0
2  20           0      (9.964, 21.667]          0
3  25           1     (21.667, 33.333]          1
4  30           1     (21.667, 33.333]          1
5  35           2       (33.333, 45.0]          2
6  40           2       (33.333, 45.0]          2
7  45           2       (33.333, 45.0]          2

### Arbitrary Discretization

In [5]:
bins = [0, 20, 35, 50]
labels = ["low", "medium", "high"]

df["x_arbitrary"] = pd.cut(df["x"], bins=bins, labels=labels)
df

    x  x_eq_width x_eq_width_intervals  x_eq_freq x_arbitrary
0  10           0      (9.964, 21.667]          0         low
1  15           0      (9.964, 21.667]          0         low
2  20           0      (9.964, 21.667]          0         low
3  25           1     (21.667, 33.333]          1      medium
4  30           1     (21.667, 33.333]          1      medium
5  35           2       (33.333, 45.0]          2      medium
6  40           2       (33.333, 45.0]          2        high
7  45           2       (33.333, 45.0]          2        high

### Binarization

In [6]:
df["x_binary"] = (df["x"] >= 30).astype(int)
df

    x  x_eq_width x_eq_width_intervals  x_eq_freq x_arbitrary  x_binary
0  10           0      (9.964, 21.667]          0         low         0
1  15           0      (9.964, 21.667]          0         low         0
2  20           0      (9.964, 21.667]          0         low         0
3  25           1     (21.667, 33.333]          1      medium         0
4  30           1     (21.667, 33.333]          1      medium         1
5  35           2       (33.333, 45.0]          2      medium         1
6  40           2       (33.333, 45.0]          2        high         1
7  45           2       (33.333, 45.0]          2        high         1