## General example

Here is a table of all variable types, which we will use as a basis to explain the different types of variables and how to work with them.

In [1]:
import pandas as pd

data = {
    "Age": [25, 30, 22, 28, 35, 40, 19, 31, 27, 33],  # Numerical
    "Gender": ["Male", "Female", "Female", "Male", "Male", 
               "Female", "Male", "Female", "Male", "Female"],  # Categorical
    "Num_Children": [0, 2, 3, 1, 0, 0, 2, 2, 3, 1],  # Categiorical
    "Signup_Date": [
        "2025-01-01", "2025-01-03", "2025-01-05", "2025-01-07", 
        "2025-01-09", "2025-01-11", "2025-01-13", "2025-01-15",
        "2025-01-17", "2025-01-19"
    ],  # Date/Time
    "Is_Active": [True, False, True, False, True, False, True, True, False, True],  # Boolean
    "Review": [
        "Great product!", "Needs improvement", "Loved it", "Not bad", 
        "Excellent", "Could be better", "Highly recommend", "Average", 
        "Terrible experience", "Will buy again"
    ],  # Text
    "Address": [
        "123 Main St, Apt 4, Boston, MA", "456 Oak St, Apt 12, NY", 
        "789 Pine St, Apt 3, Chicago, IL", "321 Maple St, Apt 9, SF, CA", 
        "654 Cedar St, Apt 1, Seattle, WA", "987 Elm St, Apt 5, Austin, TX", 
        "147 Birch St, Apt 2, Miami, FL", "258 Walnut St, Apt 8, Denver, CO", 
        "369 Chestnut St, Apt 7, Portland, OR", "159 Spruce St, Apt 6, Atlanta, GA"
    ]  # Mix
}

df = pd.DataFrame(data)
df

,Age,Gender,Num_Children,Signup_Date,Is_Active,Review,Address
0,25,Male,0,2025-01-01,True,Great product!,"123 Main St, Apt 4, Boston, MA"
1,30,Female,2,2025-01-03,False,Needs improvement,"456 Oak St, Apt 12, NY"
2,22,Female,3,2025-01-05,True,Loved it,"789 Pine St, Apt 3, Chicago, IL"
3,28,Male,1,2025-01-07,False,Not bad,"321 Maple St, Apt 9, SF, CA"
4,35,Male,0,2025-01-09,True,Excellent,"654 Cedar St, Apt 1, Seattle, WA"
5,40,Female,0,2025-01-11,False,Could be better,"987 Elm St, Apt 5, Austin, TX"
6,19,Male,2,2025-01-13,True,Highly recommend,"147 Birch St, Apt 2, Miami, FL"
7,31,Female,2,2025-01-15,True,Average,"258 Walnut St, Apt 8, Denver, CO"
8,27,Male,3,2025-01-17,False,Terrible experience,"369 Chestnut St, Apt 7, Portland, OR"
9,33,Female,1,2025-01-19,True,Will buy again,"159 Spruce St, Apt 6, Atlanta, GA"

We can quickly check the data types of the variables in a DataFrame using `dtypes`.

In [2]:
df.dtypes

Age              int64
Gender          object
Num_Children     int64
Signup_Date     object
Is_Active         bool
Review          object
Address         object
dtype: object

## Numrical

### Type Mismatches

Feature stored as one type (int) but used as another (float). For example, `Age` stored as integer, but during feature engineering you want to normalize it as a decimal. So, you need to convert the type to float in this use case.

In [3]:
df["Age"] = df["Age"].astype(float)
print(df["Age"].dtype)

float64

To revert a variable to an integer type, you can use

In [4]:
df["Age"] = df["Age"].astype(int)
print(df["Age"].dtype)

int64

### Implicit Categorical Numbers

Some numbers are categorical in disguise. `Number of children = 0,1,2,3` — small integers, but not continuous. Treating them as continuous can distort scaling or polynomial features.

In [5]:
df["Num_Children"] = df["Num_Children"].astype("category")
print(df["Num_Children"].dtype)

category

## Categorical

For analysis, we usually convert categorical variables (text-based) into numbers. There are two common methods:

1. **Ordinal Encoding:** Assigns an integer to each category, preserving a meaningful order (if one exists). We use it when the categories have a natural ranking.

In [6]:
from sklearn.preprocessing import OrdinalEncoder

data = {"Education": ["High School", "Bachelor", "Master", "PhD"]}
df_cat = pd.DataFrame(data)

ordinal_encoder = OrdinalEncoder()
df_cat["Education_Encoded"] = ordinal_encoder.fit_transform(df_cat[["Education"]])
df_cat

     Education  Education_Encoded
0  High School                1.0
1     Bachelor                0.0
2       Master                2.0
3          PhD                3.0

**2. One-Hot Encoding:** Converts each category into a separate binary column (0/1 or True/False), with no ordinal relationship implied. It is used when categories are nominal (no natural order).

In [7]:
df_cat = pd.DataFrame({"Gender": ["Male", "Female", "Female", "Male"]})

df_onehot = pd.get_dummies(df_cat, columns=["Gender"])
df_onehot

   Gender_Female  Gender_Male
0          False         True
1           True        False
2           True        False
3          False         True

### Map manually

Assign integers to categories manually using a dictionary when categories are few, and you know the mapping ahead of time. For example, Converting Gender to numbers (Male=1, Female=0)

In [8]:
df["Gender_encoded"] = df["Gender"].map({'Male': 0, 'Female': 1})
df[["Gender", "Gender_encoded"]]

   Gender  Gender_encoded
0    Male               0
1  Female               1
2  Female               1
3    Male               0
4    Male               0
5  Female               1
6    Male               0
7  Female               1
8    Male               0
9  Female               1

## Datetime

**1. Basic Conversion:** Convert a column of strings representing dates into pandas datetime format. This is prerequisit for manipulate datetime features otherwise python will treat these as string.

In [9]:
# Example column
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'])
df['Signup_Date']

0   2025-01-01
1   2025-01-03
2   2025-01-05
3   2025-01-07
4   2025-01-09
5   2025-01-11
6   2025-01-13
7   2025-01-15
8   2025-01-17
9   2025-01-19
Name: Signup_Date, dtype: datetime64[ns]

**2. Extract Components:** Extract year, month, day, weekday, and hour from a datetime column.

In [10]:
df['Year'] = df['Signup_Date'].dt.year
df['Month'] = df['Signup_Date'].dt.month
df['Day'] = df['Signup_Date'].dt.day
df['Weekday'] = df['Signup_Date'].dt.day_name()
df['Hour'] = df['Signup_Date'].dt.hour

df[["Signup_Date", "Year", "Month", "Day", "Weekday", "Hour"]]

  Signup_Date  Year  Month  Day    Weekday  Hour
0  2025-01-01  2025      1    1  Wednesday     0
1  2025-01-03  2025      1    3     Friday     0
2  2025-01-05  2025      1    5     Sunday     0
3  2025-01-07  2025      1    7    Tuesday     0
4  2025-01-09  2025      1    9   Thursday     0
5  2025-01-11  2025      1   11   Saturday     0
6  2025-01-13  2025      1   13     Monday     0
7  2025-01-15  2025      1   15  Wednesday     0
8  2025-01-17  2025      1   17     Friday     0
9  2025-01-19  2025      1   19     Sunday     0

**3. Date Differences:** Calculate the difference between two dates in days, months, or years.

In [11]:
df['Days_Since_Signup'] = (pd.Timestamp('2025-12-01') - df['Signup_Date']).dt.days
df[['Signup_Date', 'Days_Since_Signup']]

  Signup_Date  Days_Since_Signup
0  2025-01-01                334
1  2025-01-03                332
2  2025-01-05                330
3  2025-01-07                328
4  2025-01-09                326
5  2025-01-11                324
6  2025-01-13                322
7  2025-01-15                320
8  2025-01-17                318
9  2025-01-19                316

To calculate the difference between two datetime columns, you can subtract them directly. For example: `df['col1'] - df['col2']`.

In [12]:
# Current Age

df_age = pd.DataFrame({
    "Birthday": [
        "1990-05-14",
        "1985-11-02",
        "2000-01-25",
        "1997-07-09",
        "1993-03-18",
        "1988-12-30",
        "2002-09-05",
        "1995-04-21",
        "1980-06-11",
        "1999-10-27"
    ]
})

df_age["Birthday"] = pd.to_datetime(df_age["Birthday"])

df_age['Current_Age'] = (pd.Timestamp.now() - df_age['Birthday']).dt.days
df_age[['Birthday', 'Current_Age']]

    Birthday  Current_Age
0 1990-05-14        13016
1 1985-11-02        14670
2 2000-01-25         9473
3 1997-07-09        10403
4 1993-03-18        11977
5 1988-12-30        13516
6 2002-09-05         8519
7 1995-04-21        11213
8 1980-06-11        16640
9 1999-10-27         9563

**4. Filtering by Date:** Select rows within a specific date range.

In [13]:
df_filtered = df[(df['Signup_Date'] >= '2025-01-05') & (df['Signup_Date'] <= '2025-01-15')]
df_filtered

,Age,Gender,Num_Children,Signup_Date,Is_Active,Review,Address,Gender_encoded,Year,Month,Day,Weekday,Hour,Days_Since_Signup
2,22,Female,3,2025-01-05,True,Loved it,"789 Pine St, Apt 3, Chicago, IL",1,2025,1,5,Sunday,0,330
3,28,Male,1,2025-01-07,False,Not bad,"321 Maple St, Apt 9, SF, CA",0,2025,1,7,Tuesday,0,328
4,35,Male,0,2025-01-09,True,Excellent,"654 Cedar St, Apt 1, Seattle, WA",0,2025,1,9,Thursday,0,326
5,40,Female,0,2025-01-11,False,Could be better,"987 Elm St, Apt 5, Austin, TX",1,2025,1,11,Saturday,0,324
6,19,Male,2,2025-01-13,True,Highly recommend,"147 Birch St, Apt 2, Miami, FL",0,2025,1,13,Monday,0,322
7,31,Female,2,2025-01-15,True,Average,"258 Walnut St, Apt 8, Denver, CO",1,2025,1,15,Wednesday,0,320

**5. Handling Missing Dates:** Fill missing datetime values with a default value or forward/backward fill.

In [14]:
signup_df = pd.DataFrame({
    "Signup_Date": [
        "2025-01-01",
        None,
        "2025-01-05",
        None,
        "2025-01-10",
        "2025-01-12",
        None,
        "2025-01-18",
        None,
        "2025-01-20"
    ]
})

signup_df['Signup_Date'] = pd.to_datetime(signup_df['Signup_Date'])

signup_df['Signup_Date'] = signup_df['Signup_Date'].fillna(pd.Timestamp('2025-01-01'))
signup_df['Signup_Date']

0   2025-01-01
1   2025-01-01
2   2025-01-05
3   2025-01-01
4   2025-01-10
5   2025-01-12
6   2025-01-01
7   2025-01-18
8   2025-01-01
9   2025-01-20
Name: Signup_Date, dtype: datetime64[ns]

In [16]:
# or forward fill
signup_df['Signup_Date'] = signup_df['Signup_Date'].ffill()
signup_df['Signup_Date']

0   2025-01-01
1   2025-01-01
2   2025-01-05
3   2025-01-01
4   2025-01-10
5   2025-01-12
6   2025-01-01
7   2025-01-18
8   2025-01-01
9   2025-01-20
Name: Signup_Date, dtype: datetime64[ns]

**6. Sorting by Date:** Sort the DataFrame by datetime column ascending or descending.

In [18]:
df_sorted = signup_df.sort_values(by='Signup_Date', ascending=True)
df_sorted[['Signup_Date']]

  Signup_Date
0  2025-01-01
1  2025-01-01
3  2025-01-01
6  2025-01-01
8  2025-01-01
2  2025-01-05
4  2025-01-10
5  2025-01-12
7  2025-01-18
9  2025-01-20

**7. Time Delta Features:** Create features like day of week, week of year, quarter, or is_weekend.

In [20]:
df['Week_of_Year'] = df['Signup_Date'].dt.isocalendar().week
df['Quarter'] = df['Signup_Date'].dt.quarter
df['Is_Weekend'] = df['Signup_Date'].dt.weekday >= 5  # Saturday=5, Sunday=6

df[['Signup_Date', 'Week_of_Year', 'Quarter', 'Is_Weekend']]

  Signup_Date  Week_of_Year  Quarter  Is_Weekend
0  2025-01-01             1        1       False
1  2025-01-03             1        1       False
2  2025-01-05             1        1        True
3  2025-01-07             2        1       False
4  2025-01-09             2        1       False
5  2025-01-11             2        1        True
6  2025-01-13             3        1       False
7  2025-01-15             3        1       False
8  2025-01-17             3        1       False
9  2025-01-19             3        1        True

**8. Lag / Rolling Features:** Compute previous date difference, moving averages, or rolling sums.

**`rolling(window=5)`**

- it looks at the _current value + the previous 4 values_
- the window moves down _one row_ at a time

**`.diff()`**

- Computes the difference between the current row and the previous row.
- `diff(periods=2)` finds the difference between the current date and the date two rows before.

In [22]:
df['Days_Since_Last'] = df['Signup_Date'].diff().dt.days
df['7Day_Rolling'] = df['Days_Since_Last'].rolling(window=5).mean()

df[['Signup_Date', 'Days_Since_Last', '7Day_Rolling']]

  Signup_Date  Days_Since_Last  7Day_Rolling
0  2025-01-01              NaN           NaN
1  2025-01-03              2.0           NaN
2  2025-01-05              2.0           NaN
3  2025-01-07              2.0           NaN
4  2025-01-09              2.0           NaN
5  2025-01-11              2.0           2.0
6  2025-01-13              2.0           2.0
7  2025-01-15              2.0           2.0
8  2025-01-17              2.0           2.0
9  2025-01-19              2.0           2.0

**9. Extract Part of Timestamp:** Extract hour, minute, second from datetime (for event timestamp).

In [24]:
df_dt = pd.DataFrame({
    "Event_Time": [
        "2025-01-01 08:15:30",
        "2025-01-01 09:45:10",
        "2025-01-01 12:00:05",
        "2025-01-02 14:20:50",
        "2025-01-02 16:35:40",
        "2025-01-03 18:10:25",
        "2025-01-03 20:55:00",
        "2025-01-04 22:30:15",
        "2025-01-05 06:05:45",
        "2025-01-05 07:50:35"
    ]
})

df_dt["Event_Time"] = pd.to_datetime(df_dt["Event_Time"])

In [25]:
df_dt["Hour"] = df_dt["Event_Time"].dt.hour
df_dt["Minute"] = df_dt["Event_Time"].dt.minute
df_dt["Second"] = df_dt["Event_Time"].dt.second

df_dt

           Event_Time  Hour  Minute  Second
0 2025-01-01 08:15:30     8      15      30
1 2025-01-01 09:45:10     9      45      10
2 2025-01-01 12:00:05    12       0       5
3 2025-01-02 14:20:50    14      20      50
4 2025-01-02 16:35:40    16      35      40
5 2025-01-03 18:10:25    18      10      25
6 2025-01-03 20:55:00    20      55       0
7 2025-01-04 22:30:15    22      30      15
8 2025-01-05 06:05:45     6       5      45
9 2025-01-05 07:50:35     7      50      35

**10. Time Zone Conversion:** Convert naive datetime to a specific timezone.

In [28]:
df_dt['Signup_Date_TZ'] = df_dt['Event_Time']\
    .dt.tz_localize('UTC')\
        .dt.tz_convert('US/Eastern')
df_dt

           Event_Time  Hour  Minute  Second            Signup_Date_TZ
0 2025-01-01 08:15:30     8      15      30 2025-01-01 03:15:30-05:00
1 2025-01-01 09:45:10     9      45      10 2025-01-01 04:45:10-05:00
2 2025-01-01 12:00:05    12       0       5 2025-01-01 07:00:05-05:00
3 2025-01-02 14:20:50    14      20      50 2025-01-02 09:20:50-05:00
4 2025-01-02 16:35:40    16      35      40 2025-01-02 11:35:40-05:00
5 2025-01-03 18:10:25    18      10      25 2025-01-03 13:10:25-05:00
6 2025-01-03 20:55:00    20      55       0 2025-01-03 15:55:00-05:00
7 2025-01-04 22:30:15    22      30      15 2025-01-04 17:30:15-05:00
8 2025-01-05 06:05:45     6       5      45 2025-01-05 01:05:45-05:00
9 2025-01-05 07:50:35     7      50      35 2025-01-05 02:50:35-05:00

**11. String Parsing:** Convert non-standard date formats into datetime. Here’s a table showing common datetime string examples and their corresponding `format= strings` for `pd.to_datetime()`.

| Date String Example       | format= String        |
| ------------------------- | --------------------- |
| 01-Jan-2025 08:15 AM      | %d-%b-%Y %I:%M %p     |
| 2025/01/01 14:30          | %Y/%m/%d %H:%M        |
| 15 March 2025 07:05 PM    | %d %B %Y %I:%M %p     |
| 03-04-25 23:59            | %d-%m-%y %H:%M        |
| Mon, 01 Jan 2025 08:15:30 | %a, %d %b %Y %H:%M:%S |
| 2025-12-01T14:30:00       | %Y-%m-%dT%H:%M:%S     |
| 01/12/2025 08:00          | %d/%m/%Y %H:%M        |
| Jan 1, 2025 8:15 AM       | %b %d, %Y %I:%M %p    |
| 20251201 143000           | %Y%m%d %H%M%S         |
| Sunday, 01 December 2025  | %A, %d %B %Y          |

In [36]:
df_dt2 = pd.DataFrame({
    "Event_Time": [
        "01-Jan-2025 08:15 AM",
        "02-Feb-2025 14:45 PM",
        "15-Mar-2025 23:30 PM",
        "04-Apr-2025 07:05 AM",
        "12-May-2025 19:50 PM"
    ]
})

df_dt2["Event_Time"] = pd.to_datetime(df_dt2["Event_Time"], format="%d-%b-%Y %H:%M %p")
df_dt2["Event_Time"]

0   2025-01-01 08:15:00
1   2025-02-02 14:45:00
2   2025-03-15 23:30:00
3   2025-04-04 07:05:00
4   2025-05-12 19:50:00
Name: Event_Time, dtype: datetime64[ns]

In [37]:
# Extract date only
df_dt2['Event_Time'].dt.date

0    2025-01-01
1    2025-02-02
2    2025-03-15
3    2025-04-04
4    2025-05-12
Name: Event_Time, dtype: object

In [39]:
# Extract time only
df_dt['Event_Time'].dt.time

0    08:15:30
1    09:45:10
2    12:00:05
3    14:20:50
4    16:35:40
5    18:10:25
6    20:55:00
7    22:30:15
8    06:05:45
9    07:50:35
Name: Event_Time, dtype: object

**Converting to specific format**
After you have a pandas datetime column, you can format it exactly the way you want using `.dt.strftime()`.

In [43]:
# original values
df_dt['Event_Time']

0   2025-01-01 08:15:30
1   2025-01-01 09:45:10
2   2025-01-01 12:00:05
3   2025-01-02 14:20:50
4   2025-01-02 16:35:40
5   2025-01-03 18:10:25
6   2025-01-03 20:55:00
7   2025-01-04 22:30:15
8   2025-01-05 06:05:45
9   2025-01-05 07:50:35
Name: Event_Time, dtype: datetime64[ns]

In [44]:
# formatted values
df_dt['Event_Time'].dt.strftime('%d-%b-%Y %I:%M %p')

0    01-Jan-2025 08:15 AM
1    01-Jan-2025 09:45 AM
2    01-Jan-2025 12:00 PM
3    02-Jan-2025 02:20 PM
4    02-Jan-2025 04:35 PM
5    03-Jan-2025 06:10 PM
6    03-Jan-2025 08:55 PM
7    04-Jan-2025 10:30 PM
8    05-Jan-2025 06:05 AM
9    05-Jan-2025 07:50 AM
Name: Event_Time, dtype: object

In [50]:
df_dt['Event_Time'].dt.day_name()

0    Wednesday
1    Wednesday
2    Wednesday
3     Thursday
4     Thursday
5       Friday
6       Friday
7     Saturday
8       Sunday
9       Sunday
Name: Event_Time, dtype: object

**12. Mixed Date and Datetime:** Sometimes, a single variable may contain values in both date and datetime formats. If we try to convert them directly to a single datetime format, it can raise an error. To handle this, we can use `errors='coerce'`, which converts any incompatible values to `NaT` — pandas’ equivalent of NaN for datetime objects.

In [ ]:
mixed_df = pd.DataFrame({
    "Event": [
        "2025-01-01",
        None,
        "2025-01-05 08:15:30",
        None,
        "2025-01-10",
        "2025-01-12 20:55:00",
        None,
        "2025-01-18 06:05:45",
        None,
        "2025-01-20"
    ]
})

In [68]:
pd.to_datetime(mixed_df["Event"], errors='coerce')

0   2025-01-01
1          NaT
2          NaT
3          NaT
4   2025-01-10
5          NaT
6          NaT
7          NaT
8          NaT
9   2025-01-20
Name: Event, dtype: datetime64[ns]

The solution is to format all values consistently using `format='mixed'`. Since the column contains null values, we should apply this formatting only to the non-null entries to avoid errors.

In [69]:
mixed_df = pd.to_datetime(mixed_df["Event"], format='mixed')
mixed_df

0   2025-01-01 00:00:00
1                   NaT
2   2025-01-05 08:15:30
3                   NaT
4   2025-01-10 00:00:00
5   2025-01-12 20:55:00
6                   NaT
7   2025-01-18 06:05:45
8                   NaT
9   2025-01-20 00:00:00
Name: Event, dtype: datetime64[ns]