# Multivariate Imputation Examples in Python

We will show examples of handling missing values using **KNN imputation** and **MICE** with `sklearn`.

In [ ]:
import numpy as np
import pandas as pd
# IterativeImputer is considered experimental in some versions (<=0.24)
# and needs a special import before you can use it.
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import KNNImputer, IterativeImputer

data = {
    'Age': [25, 30, np.nan, 35, 40],
    'Salary': [50000, 60000, 65000, np.nan, 80000],
    'Experience': [2, 5, 7, 10, np.nan]
}
df = pd.DataFrame(data)
df

Original Data:

    Age   Salary  Experience
0  25.0  50000.0         2.0
1  30.0  60000.0         5.0
2   NaN  65000.0         7.0
3  35.0      NaN        10.0
4  40.0  80000.0         NaN

### KNN Imputation

In [5]:
knn_imputer = KNNImputer(n_neighbors=2)
df_knn_imputed = knn_imputer.fit_transform(df)

df_knn_imputed = pd.DataFrame(df_knn_imputed, columns=df.columns)
print("\nKNN Imputed Data:")
df_knn_imputed

KNN Imputed Data:

    Age   Salary  Experience
0  25.0  50000.0         2.0
1  30.0  60000.0         5.0
2  32.5  65000.0         7.0
3  35.0  62500.0        10.0
4  40.0  80000.0         7.5

- Good for datasets where similar rows are expected to have similar values.

### MICE Imputation (IterativeImputer)

In [6]:
mice_imputer = IterativeImputer(max_iter=10, random_state=0)
df_mice_imputed = mice_imputer.fit_transform(df)

df_mice_imputed = pd.DataFrame(df_mice_imputed, columns=df.columns)
print("\nMICE Imputed Data:")
df_mice_imputed

MICE Imputed Data:

         Age        Salary  Experience
0  25.000000  50000.000000    2.000000
1  30.000000  60000.000000    5.000000
2  32.508437  65000.000000    7.000000
3  35.000000  70003.728473   10.000000
4  40.000000  80000.000000   13.279461

- Generates more statistically robust imputations, especially when variables are correlated.