In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import category_encoders as ce

data = {
    'Fruit': ['Apple', 'Banana', 'Apple', 'Orange', 'Apple', 'Banana', 'Orange', 'Banana', 'Apple'],
    'Size': ['Small', 'Medium', 'Large', 'Small', 'Large', 'Medium', 'Large', 'Small', 'Medium'],
    'Price': [1.2, 0.8, 1.3, 1.5, 1.1, 0.9, 1.6, 0.85, 1.25],
    'Sales': [100, 150, 120, 80, 110, 160, 70, 155, 115]
}
df = pd.DataFrame(data)
df

    Fruit    Size  Price  Sales
0   Apple   Small   1.20    100
1  Banana  Medium   0.80    150
2   Apple   Large   1.30    120
3  Orange   Small   1.50     80
4   Apple   Large   1.10    110
5  Banana  Medium   0.90    160
6  Orange   Large   1.60     70
7  Banana   Small   0.85    155
8   Apple  Medium   1.25    115

In [2]:
X = df[['Fruit', 'Size', 'Price']]
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

## Target / Mean Encoding

In [3]:
target_enc = ce.TargetEncoder(cols=['Fruit', 'Size'])
target_enc.fit(X_train, y_train)
X_train_encoded = target_enc.transform(X_train)
X_test_encoded = target_enc.transform(X_test)

X_train_encoded

        Fruit        Size  Price
4  106.219496  103.587358   1.10
8  106.219496  110.325284   1.25
6  101.459592  103.587358   1.60
3  101.459592  103.587358   1.50
0  106.219496  103.587358   1.20
5  112.880876  110.325284   0.90

## Leave-One-Out Encoding

In [4]:
loo_enc = ce.LeaveOneOutEncoder(cols=['Fruit', 'Size'])
loo_enc.fit(X_train, y_train)
X_train_loo = loo_enc.transform(X_train)
X_test_loo = loo_enc.transform(X_test)

X_train_loo

        Fruit   Size  Price
4  108.333333   90.0   1.10
8  108.333333  137.5   1.25
6   75.000000   90.0   1.60
3   75.000000   90.0   1.50
0  108.333333   90.0   1.20
5  105.833333  137.5   0.90

## Binary / Base-N Encoding

In [5]:
binary_enc = ce.BinaryEncoder(cols=['Fruit', 'Size'])
binary_enc.fit(X_train)
X_train_bin = binary_enc.transform(X_train)
X_test_bin = binary_enc.transform(X_test)

X_train_bin

   Fruit_0  Fruit_1  Size_0  Size_1  Price
4        0        1       0       1   1.10
8        0        1       1       0   1.25
6        1        0       0       1   1.60
3        1        0       1       1   1.50
0        0        1       1       1   1.20
5        1        1       1       0   0.90

## Hashing / Feature Hashing

In [6]:
hash_enc = ce.HashingEncoder(cols=['Fruit', 'Size'], n_components=3)
hash_enc.fit(X_train)
X_train_hash = hash_enc.transform(X_train)
X_test_hash = hash_enc.transform(X_test)

X_train_hash

   col_0  col_1  col_2  Price
4      0      2      0   1.10
8      1      1      0   1.25
6      1      1      0   1.60
3      1      0      1   1.50
0      0      1      1   1.20
5      1      0      1   0.90

## CatBoost / Monotonic Encoding

In [7]:
catboost_enc = ce.CatBoostEncoder(cols=['Fruit', 'Size'])
catboost_enc.fit(X_train, y_train)
X_train_cb = catboost_enc.transform(X_train)
X_test_cb = catboost_enc.transform(X_test)

X_train_cb

        Fruit        Size  Price
4  107.708333   95.277778   1.10
8  107.708333  126.944444   1.25
6   85.277778   95.277778   1.60
3   85.277778   95.277778   1.50
0  107.708333   95.277778   1.20
5  105.833333  126.944444   0.90