In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

df = pd.DataFrame({
    'age': [25, 32, None, 40, 28],
    'income': [50000, 60000, 55000, None, 70000],
    'gender': ['female', None, None, 'male', 'male']
})

df

    age   income  gender
0  25.0  50000.0  female
1  32.0  60000.0    None
2   NaN  55000.0    None
3  40.0      NaN    male
4  28.0  70000.0    male

In [2]:
# Median imputer
median_imputer = SimpleImputer(strategy='median')
median_imputer.fit_transform(df[['age']])

array([[25.],
       [32.],
       [30.],
       [40.],
       [28.]])

In [3]:
# Mean imputer
median_imputer = SimpleImputer(strategy='mean')
median_imputer.fit_transform(df[['age']])

array([[25.  ],
       [32.  ],
       [31.25],
       [40.  ],
       [28.  ]])

In [4]:
# Fill missing values with -999
arbitrary_imputer = SimpleImputer(strategy='constant', fill_value=-999)
arbitrary_imputer.fit_transform(df[['income']])

array([[50000.],
       [60000.],
       [55000.],
       [ -999.],
       [70000.]])

In [5]:
# Fill missing categorical values with 'female'
cat_arbitrary_imputer = SimpleImputer(strategy='constant', fill_value='female')
cat_arbitrary_imputer.fit_transform(df[['gender']])

array([['female'],
       [None],
       [None],
       ['male'],
       ['male']], dtype=object)

`SimpleImputer` does not recognize `None` as a missing value for object arrays unless you explicitly tell it using the `missing_values` parameter.

In [6]:
cat_arbitrary_imputer = SimpleImputer(strategy='constant', fill_value='female', missing_values=None)
cat_arbitrary_imputer.fit_transform(df[['gender']])

array([['female'],
       ['female'],
       ['female'],
       ['male'],
       ['male']], dtype=object)

In [7]:
# Mode / Most Frequent Imputation
mode_imputer = SimpleImputer(strategy='most_frequent')
mode_imputer.fit_transform(df[['age']])

array([[25.],
       [32.],
       [25.],
       [40.],
       [28.]])

In [8]:
# Complete Case Analysis (CCA)
from sklearn.preprocessing import FunctionTransformer

drop_rows = FunctionTransformer(lambda X: X.dropna(), validate=False)
df_clean = drop_rows.transform(df)
df_clean

    age   income  gender
0  25.0  50000.0  female
4  28.0  70000.0    male

In [9]:
# End of Distribution Imputation
# Replace missing numeric values with max + 1000
end_of_dist_imputer = SimpleImputer(strategy='constant', fill_value=df['income'].max() + 1000)
end_of_dist_imputer.fit_transform(df[['income']])

array([[50000.],
       [60000.],
       [55000.],
       [71000.],
       [70000.]])

In [10]:
# Random Sample Imputation
from sklearn.preprocessing import FunctionTransformer

def random_sample_impute(X):
    X = X.copy()
    for col in X.columns:
        na_mask = X[col].isna()
        X.loc[na_mask, col] = np.random.choice(X.loc[~na_mask, col], size=na_mask.sum())
    return X

random_imputer = FunctionTransformer(random_sample_impute, validate=False)
random_imputer.transform(df)

    age   income  gender
0  25.0  50000.0  female
1  32.0  60000.0    male
2  25.0  55000.0    male
3  40.0  70000.0    male
4  28.0  70000.0    male

In [11]:
from sklearn.impute import MissingIndicator

indicator = MissingIndicator()
indicator.fit_transform(df[['age', 'income']])

array([[False, False],
       [False, False],
       [ True, False],
       [False,  True],
       [False, False]])